CREATE TABLE EMPLOYEE_TABLE(
EMPLOYEE_POSITION VARCHAR(12),
EMPLOYEE_NAME VARCHAR(12),
EMAIL VARCHAR(30),
ADDRESS VARCHAR(12),
PHONE_NUMBER NUMERIC(13) PRIMARY KEY);

CREATE TABLE MANAGER_TABLE(
MANAGER_POSITION VARCHAR(12),
MANAGER_NAME VARCHAR(12),
EMAIL VARCHAR(30),
ADDRESS VARCHAR(12),
PHONE_NUMBER  NUMERIC(13) PRIMARY KEY);

ALTER TABLE EMPLOYEE_TABLE ADD CONSTRAINT
MANAGER_TABLE FOREIGN KEY (PHONE_NUMBER) REFERENCES EMPLOYEE_TABLE;